# Generated by Django 5.0.6 on 2026-06-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=128)),
                ('source', models.CharField(choices=[('systemd-journald', 'Systemd Journald'), ('syslog', 'Syslog'), ('kernel', 'Kernel'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('internal', 'Beacon Internal')], db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('Trace', 'Trace'), ('Debug', 'Debug'), ('Info', 'Info'), ('Warning', 'Warning'), ('Error', 'Error'), ('Critical', 'Critical')], db_index=True, max_length=16)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('sequence_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'beacon_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent_id', 'severity', 'timestamp'], name='beacon_logs_agent_i_06fd03_idx'), models.Index(fields=['agent_id', 'source', 'timestamp'], name='beacon_logs_agent_i_fdeffd_idx')],
            },
        ),
    ]
