# Generated by Django 5.0.6 on 2026-06-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ONLINE', max_length=32)),
                ('agents_online', models.IntegerField(default=0)),
                ('agents_total', models.IntegerField(default=0)),
                ('metrics_rate', models.FloatField(default=0.0)),
                ('logs_rate', models.FloatField(default=0.0)),
                ('db_size_bytes', models.BigIntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'beacon_server_health',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
