# Generated by Django 5.0.6 on 2026-06-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasaimessage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
