# Generated by Django 5.0.6 on 2026-06-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('resource', models.CharField(db_index=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=256)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'beacon_audit_log',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
    ]
