# Generated by Django 5.0.6 on 2026-06-11 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('hostname', models.CharField(max_length=253)),
                ('os', models.CharField(default='linux', max_length=64)),
                ('architecture', models.CharField(default='x86_64', max_length=32)),
                ('version', models.CharField(default='unknown', max_length=32)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('BOOTING', 'Booting'), ('INITIALIZING', 'Initializing'), ('ONLINE', 'Online'), ('DEGRADED', 'Degraded'), ('OFFLINE_BUFFERING', 'Offline (Buffering)'), ('RECOVERING', 'Recovering'), ('FAILED', 'Failed'), ('SHUTTING_DOWN', 'Shutting Down'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('secret_hash', models.CharField(blank=True, max_length=256)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'beacon_agents',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='CollectorHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Healthy', 'Healthy'), ('Degraded', 'Degraded'), ('Failed', 'Failed'), ('Disabled', 'Disabled')], default='Healthy', max_length=16)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('last_failure', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_health', to='agents.agent')),
            ],
            options={
                'db_table': 'beacon_collector_health',
                'unique_together': {('agent', 'collector')},
            },
        ),
    ]
