# Generated by Django 5.0.6 on 2026-06-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_processkillrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processkillrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='processkillrequest',
            index=models.Index(fields=['agent_id', 'status', 'created_at'], name='beacon_proc_agent_i_534890_idx'),
        ),
    ]
