# Generated by Django 5.0.6 on 2026-06-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('cpu_enabled', models.BooleanField(default=True)),
                ('ram_enabled', models.BooleanField(default=True)),
                ('storage_enabled', models.BooleanField(default=True)),
                ('network_enabled', models.BooleanField(default=True)),
                ('process_enabled', models.BooleanField(default=True)),
                ('systemd_enabled', models.BooleanField(default=True)),
                ('docker_enabled', models.BooleanField(default=False)),
                ('kubernetes_enabled', models.BooleanField(default=False)),
                ('temperature_enabled', models.BooleanField(default=True)),
                ('power_enabled', models.BooleanField(default=False)),
                ('interval_seconds', models.PositiveIntegerField(default=5)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beacon_metric_config',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=128)),
                ('metric_type', models.CharField(choices=[('cpu', 'CPU'), ('ram', 'RAM'), ('storage', 'Storage'), ('network', 'Network'), ('process', 'Process'), ('systemd', 'Systemd'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('kernel', 'Kernel'), ('temperature', 'Temperature'), ('power', 'Power')], db_index=True, max_length=32)),
                ('resolution', models.CharField(choices=[('raw', 'Raw (1s)'), ('1min', '1 Minute Rollup'), ('1hour', '1 Hour Rollup')], db_index=True, default='raw', max_length=8)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('data', models.JSONField()),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
            ],
            options={
                'db_table': 'beacon_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent_id', 'metric_type', 'timestamp'], name='beacon_metr_agent_i_70f597_idx'), models.Index(fields=['agent_id', 'resolution', 'timestamp'], name='beacon_metr_agent_i_eeba9f_idx')],
            },
        ),
    ]
