# Generated by Django 5.0.6 on 2026-06-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_system_inventory_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='metric_type',
            field=models.CharField(choices=[('cpu', 'CPU'), ('ram', 'RAM'), ('storage', 'Storage'), ('network', 'Network'), ('process', 'Process'), ('systemd', 'Systemd'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('kernel', 'Kernel'), ('temperature', 'Temperature'), ('power', 'Power'), ('system_inventory', 'System Inventory')], db_index=True, max_length=32),
        ),
    ]
