# Generated by Django 5.0.6 on 2026-06-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dockercontainer',
            new_name='operations__agent_i_bc39e3_idx',
            old_name='operations__agent_i_ada99a_idx',
        ),
        migrations.RenameIndex(
            model_name='kubernetespod',
            new_name='operations__agent_i_d4c19d_idx',
            old_name='operations__agent_i_a69a28_idx',
        ),
        migrations.RenameIndex(
            model_name='networkconnection',
            new_name='operations__agent_i_2844ee_idx',
            old_name='operations__agent_i_fbe4f4_idx',
        ),
        migrations.RenameIndex(
            model_name='networkconnection',
            new_name='operations__agent_i_d46f8c_idx',
            old_name='operations__agent_i_01c0bb_idx',
        ),
        migrations.RenameIndex(
            model_name='processsnapshot',
            new_name='operations__agent_i_1adcdf_idx',
            old_name='operations__agent_i_d4226f_idx',
        ),
        migrations.RenameIndex(
            model_name='processsnapshot',
            new_name='operations__agent_i_798e32_idx',
            old_name='operations__agent_i_b556b6_idx',
        ),
    ]
